shared_routes:
  resource: '../../src/Shared/Infrastructure/Symfony/Controller/'
  type: attribute

third_party_routes:
    resource: '../../src/Shared/Infrastructure/ThirdPartyServices/Controller/'
    type: attribute

user_routes:
  resource: '../../src/User/Infrastructure/Symfony/Controller/'
  type: attribute

book_routes:
  resource: '../../src/Book/Infrastructure/Symfony/Controller/'
  type: attribute

authentication_routes:
  resource: '../../src/Authentication/Infrastructure/Symfony/Controller/'
  type: attribute