shared_routes:
  resource: '../../src/Shared/Infrastructure/Symfony/Controller/'
  type: attribute

user_routes:
  resource: '../../src/User/Infrastructure/Symfony/Controller/'
  type: attribute

book_routes:
  resource: '../../src/Book/Infrastructure/Symfony/Controller/'
  type: attribute